from collections import Counter


def generate_summary_html(daily_tweets: list, mentioned_accounts: dict, recommendations: list) -> str:
    """Build an HTML email body summarizing the day's tweets."""
    if not daily_tweets:
        return "<h2>FinTwit Daily Summary</h2><p>No tweets today.</p>"

    # --- aggregate stats ---
    by_user: dict[str, list] = {}
    all_text = []
    for t in daily_tweets:
        by_user.setdefault(t["user"], []).append(t)
        all_text.append(t["text"])

    total = len(daily_tweets)
    total_engagement = sum(
        t["likes"] + t["retweets"] + t["replies"] for t in daily_tweets
    )

    # --- top tweets by engagement ---
    ranked = sorted(
        daily_tweets,
        key=lambda t: t["likes"] + t["retweets"] + t["replies"],
        reverse=True,
    )
    top_tweets = ranked[:10]

    # --- simple keyword / theme extraction ---
    themes = _extract_themes(all_text)

    # --- build HTML ---
    html_parts = [
        "<div style='font-family: Arial, sans-serif; max-width: 700px; margin: auto;'>",
        "<h1 style='border-bottom: 2px solid #1da1f2; padding-bottom: 8px;'>FinTwit Daily Summary</h1>",
        f"<p><strong>{total}</strong> tweets from <strong>{len(by_user)}</strong> account(s) "
        f"| Total engagement: <strong>{total_engagement:,}</strong></p>",
    ]

    # themes
    if themes:
        html_parts.append("<h2>Key Themes</h2><ul>")
        for theme in themes[:8]:
            html_parts.append(f"<li>{theme}</li>")
        html_parts.append("</ul>")

    # per-account breakdown
    html_parts.append("<h2>Account Activity</h2>")
    for user, tweets in sorted(by_user.items()):
        eng = sum(t["likes"] + t["retweets"] + t["replies"] for t in tweets)
        html_parts.append(
            f"<p><strong>@{user}</strong> &mdash; {len(tweets)} tweets, "
            f"{eng:,} total engagement</p>"
        )

    # top tweets
    html_parts.append("<h2>Top Tweets</h2>")
    for i, t in enumerate(top_tweets, 1):
        text_preview = t["text"][:280]
        eng = t["likes"] + t["retweets"] + t["replies"]
        html_parts.append(
            f"<div style='border-left: 3px solid #1da1f2; padding: 8px 12px; margin: 12px 0;'>"
            f"<strong>#{i}</strong> &mdash; <a href=\"{t['url']}\">@{t['user']}</a> "
            f"({eng:,} engagement)<br>"
            f"<span style='color: #333;'>{text_preview}</span>"
            f"</div>"
        )

    # recommendations
    if recommendations:
        html_parts.append("<h2>Suggested Accounts to Follow</h2>")
        html_parts.append(
            "<p>These accounts were frequently mentioned or retweeted by your follows today:</p><ol>"
        )
        for username, count in recommendations:
            html_parts.append(
                f"<li><a href='https://x.com/{username}'>@{username}</a> "
                f"&mdash; mentioned {count} time(s)</li>"
            )
        html_parts.append("</ol>")

    html_parts.append(
        "<hr><p style='color:#888; font-size:12px;'>Generated by FinTwit Monitor</p></div>"
    )
    return "\n".join(html_parts)


def _extract_themes(texts: list[str]) -> list[str]:
    """Very basic keyword frequency to surface themes."""
    stop = {
        "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
        "have", "has", "had", "do", "does", "did", "will", "would", "could",
        "should", "may", "might", "shall", "can", "need", "dare", "ought",
        "used", "to", "of", "in", "for", "on", "with", "at", "by", "from",
        "as", "into", "through", "during", "before", "after", "above",
        "below", "between", "out", "off", "over", "under", "again",
        "further", "then", "once", "here", "there", "when", "where", "why",
        "how", "all", "both", "each", "few", "more", "most", "other",
        "some", "such", "no", "nor", "not", "only", "own", "same", "so",
        "than", "too", "very", "just", "don", "now", "and", "but", "or",
        "if", "it", "its", "he", "she", "they", "them", "his", "her",
        "their", "this", "that", "these", "those", "i", "me", "my", "we",
        "our", "you", "your", "what", "which", "who", "whom", "rt", "amp",
        "via", "like", "get", "got", "us", "up", "about",
    }
    words: list[str] = []
    for text in texts:
        for word in text.split():
            w = word.strip(".,!?:;\"'()[]{}#@").lower()
            if len(w) > 2 and w not in stop and not w.startswith("http"):
                words.append(w)

    counts = Counter(words)
    return [word for word, _ in counts.most_common(8)]
